/**
 * This file is auto-generated by idlpp
 *
 * Source: HelloWorld.idl
 * Generated on: 2020-11-05T15:40:33+0100
 * OpenSplice 6.10.4p2
 */
#if defined (__cplusplus)
extern "C" {
#endif

#include "HelloWorldSacDcps.h"

#if defined (__cplusplus)
}
#endif
