module RevPiDDS {
  struct Tasks {
    long taskID;
    string message;
  };
  #pragma keylist Tasks taskID

  struct Actors {
    string address;
    string role;
  };
  #pragma keylist Actors address

  struct Decision {
    string message;
  };
  #pragma keylist Decision message
};
