module RevPiDDS {
  struct Task {
    long taskType;
  };
  #pragma keylist Task taskType

  struct Decision {
    long senderID;
    long decision;
  };
  #pragma keylist Decision senderID

  struct State {
    long timestamp;
    double speed;
  };
  #pragma keylist State timestamp
};
