module RevPiDDS {
  struct Task {
    long taskType;
  };
  #pragma keylist Task taskType

  struct Decision {
    long decisionID;
  };
  #pragma keylist Decision decisionID

  struct State {
    long timestamp;
    double speed;
  };
  #pragma keylist State timestamp
};
