module RevPiDDS {

  struct Entry {
    long id;
  };

  struct Input {
    long id;
  };
  #pragma keylist Input id
  
  struct AppendEntries {
    long term;
    long senderID;
    sequence<Entry> entries;
  };
  #pragma keylist AppendEntries term

  struct AppendEntriesReply {
    long senderID;
    long id;
    long term;
    boolean success;
  };
  #pragma keylist AppendEntriesReply

  struct RequestVote {
    long term;
    long senderID;
  };
  #pragma keylist RequestVote

  struct RequestVoteReply {
    long senderID;
    long term;
    long candidateID;
    boolean voteGranted;
  };
  #pragma keylist RequestVoteReply

  struct ReplicaResult {
    long senderID;
    long temp;
  };
  #pragma keylist ReplicaResult

  struct ActivateSpare {
    long term;
    boolean activate;
  };
  #pragma keylist ActivateSpare

};
