module RevPiDDS {

  struct Input {
    long id;
    sequence<long> data;
  };
  #pragma keylist Input id

  struct TrainState {
    double position;
    double max_position;
    double min_position;
    float speed;
    unsigned long long lastUpdateTime;
  };
  #pragma keylist TrainState

};
